package ra04_gestion_datos_y_aplicaciones.u07_coleccioneDinámicasDatos.Maps;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Diccionario {
    static HashMap<String, String> map = new HashMap<>();
    static Scanner teclado = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("*** Diccionario Español - Ingles ***");

        map = getMap();

        int preguntas = 0;
        int aciertos = 0;
        int errores = 0;

        while (true) {
            String palabraAleat = palabrasAleatorias();
            System.out.println(palabraAleat + ": " + primeraLetraTraduccion(palabraAleat) + "...");
            System.out.println("Indique la respuesta:");
            String respuesta = teclado.next();

            if (respuesta.equals("fin")) {
                break;
            }

            preguntas++;
            String correcta = traduce(palabraAleat, respuesta);

            if (respuesta.equals(correcta)) {
                aciertos++;
            } else {
                errores++;
            }
        }

        int porcentaje = 0;
        if (preguntas > 0) {
            porcentaje = (aciertos * 100) / preguntas;
        }

        System.out.println("FIN DEL PROGRAMA");
        System.out.println("Total preguntas: " + preguntas);
        System.out.println("Total aciertos: " + aciertos);
        System.out.println("Total errores: " + errores);
        System.out.println("Aciertos: " + porcentaje + "%");
    }

    public static void nuevoPar() {
    }

    public static String traduce(String palabraAleat, String respuesta) {
        String palabraIngles = map.get(palabraAleat);
        if (respuesta.equals(palabraIngles)) {
            System.out.println("¡CORRECTO!");
        } else {
            System.out.println("¡NO! La respuesta correcta es " + palabraIngles);
        }
        return palabraIngles;
    }

    public static String palabrasAleatorias() {
        List<String> claves = new ArrayList<>(map.keySet());
        Random random = new Random();
        String palabraAleat = claves.get(random.nextInt(claves.size()));
        return palabraAleat;
    }

    public static String primeraLetraTraduccion(String palabraAleat) {
        String primerLet = String.valueOf(map.get(palabraAleat).charAt(0));
        return primerLet;
    }

    public static HashMap<String, String> getMap() {
        HashMap<String, String> map = new HashMap<>();


                    // A
                    map.put("abandonar", "abandon");
                    map.put("habilidad", "ability");
                    map.put("capaz", "able");
                    map.put("encima", "above");
                    map.put("ausencia", "absence");
                    map.put("aceptar", "accept");
                    map.put("accidente", "accident");
                    map.put("cuenta", "account");
                    map.put("lograr", "achieve");
                    map.put("ácido", "acid");
                    map.put("actuar", "act");
                    map.put("acción", "action");
                    map.put("añadir", "add");
                    map.put("dirección", "address");
                    map.put("adulto", "adult");
                    map.put("avanzar", "advance");
                    map.put("consejo", "advice");
                    map.put("asustado", "afraid");
                    map.put("edad", "age");
                    map.put("acordar", "agree");
                    map.put("acuerdo", "agreement");
                    map.put("aire", "air");
                    map.put("aeropuerto", "airport");
                    map.put("vivo", "alive");
                    map.put("permitir", "allow");
                    map.put("solo", "alone");
                    map.put("ya", "already");
                    map.put("aunque", "although");
                    map.put("siempre", "always");
                    map.put("ambición", "ambition");
                    map.put("cantidad", "amount");
                    map.put("ancla", "anchor");
                    map.put("ira", "anger");
                    map.put("animal", "animal");
                    map.put("respuesta", "answer");
                    map.put("apartamento", "apartment");
                    map.put("manzana", "apple");
                    map.put("aplicar", "apply");
                    map.put("brazo", "arm");
                    map.put("ejército", "army");
                    map.put("llegada", "arrival");
                    map.put("llegar", "arrive");
                    map.put("arte", "art");
                    map.put("preguntar", "ask");
                    map.put("atención", "attention");
                    map.put("tía", "aunt");
                    map.put("otoño", "autumn");
                    map.put("disponible", "available");
                    map.put("premio", "award");
                    map.put("horrible", "awful");

                    // B
                    map.put("bebé", "baby");
                    map.put("espalda / atrás", "back");
                    map.put("bolsa", "bag");
                    map.put("pelota", "ball");
                    map.put("plátano", "banana");
                    map.put("banco", "bank");
                    map.put("baño", "bath");
                    map.put("batalla", "battle");
                    map.put("playa", "beach");
                    map.put("oso", "bear");
                    map.put("barba", "beard");
                    map.put("hermoso", "beautiful");
                    map.put("porque", "because");
                    map.put("convertirse", "become");
                    map.put("cama", "bed");
                    map.put("empezar", "begin");
                    map.put("creer", "believe");
                    map.put("debajo", "below");
                    map.put("beneficio", "benefit");
                    map.put("entre", "between");
                    map.put("bicicleta", "bicycle");
                    map.put("pájaro", "bird");
                    map.put("morder", "bite");
                    map.put("negro", "black");
                    map.put("manta", "blanket");
                    map.put("ciego", "blind");
                    map.put("sangre", "blood");
                    map.put("azul", "blue");
                    map.put("barco", "boat");
                    map.put("cuerpo", "body");
                    map.put("libro", "book");
                    map.put("frontera", "border");
                    map.put("nacer", "born");
                    map.put("botella", "bottle");
                    map.put("caja", "box");
                    map.put("niño", "boy");
                    map.put("valiente", "brave");
                    map.put("pan", "bread");
                    map.put("romper", "break");
                    map.put("puente", "bridge");
                    map.put("brillante", "bright");
                    map.put("hermano", "brother");
                    map.put("marrón", "brown");
                    map.put("construir", "build");
                    map.put("edificio", "building");
                    map.put("quemar", "burn");
                    map.put("ocupado", "busy");
                    map.put("mantequilla", "butter");
                    map.put("botón", "button");
                    map.put("comprar", "buy");

                    // C
                    map.put("llamar", "call");
                    map.put("calma", "calm");
                    map.put("cámara", "camera");
                    map.put("campamento", "camp");
                    map.put("coche", "car");
                    map.put("cuidado", "care");
                    map.put("llevar", "carry");
                    map.put("castillo", "castle");
                    map.put("gato", "cat");
                    map.put("atrapar", "catch");
                    map.put("causa", "cause");
                    map.put("cueva", "cave");
                    map.put("celebrar", "celebrate");
                    map.put("silla", "chair");
                    map.put("cambiar", "change");
                    map.put("carácter", "character");
                    map.put("barato", "cheap");
                    map.put("comprobar", "check");
                    map.put("queso", "cheese");
                    map.put("pecho", "chest");
                    map.put("niño", "child");
                    map.put("elección", "choice");
                    map.put("elegir", "choose");
                    map.put("círculo", "circle");
                    map.put("ciudad", "city");
                    map.put("clase", "class");
                    map.put("limpio", "clean");
                    map.put("claro", "clear");
                    map.put("escalar", "climb");
                    map.put("reloj", "clock");
                    map.put("cerrar", "close");
                    map.put("nube", "cloud");
                    map.put("abrigo", "coat");
                    map.put("frío", "cold");
                    map.put("color", "color");
                    map.put("venir", "come");
                    map.put("comodidad", "comfort");
                    map.put("empresa", "company");
                    map.put("completar", "complete");
                    map.put("ordenador", "computer");
                    map.put("condición", "condition");
                    map.put("conectar", "connect");
                    map.put("controlar", "control");
                    map.put("cocinar", "cook");
                    map.put("esquina", "corner");
                    map.put("correcto", "correct");
                    map.put("costo", "cost");
                    map.put("país", "country");
                    map.put("pareja", "couple");
                    map.put("valor", "courage");
                    map.put("cubrir", "cover");
                    map.put("crear", "create");
                    map.put("cruzar", "cross");
                    map.put("multitud", "crowd");
                    map.put("llorar", "cry");
                    map.put("cultura", "culture");
                    map.put("taza", "cup");
                    map.put("cortar", "cut");

                    // D
                    map.put("bailar", "dance");
                    map.put("peligro", "danger");
                    map.put("oscuro", "dark");
                    map.put("hija", "daughter");
                    map.put("día", "day");
                    map.put("muerto", "dead");
                    map.put("trato", "deal");
                    map.put("decidir", "decide");
                    map.put("decisión", "decision");
                    map.put("profundo", "deep");
                    map.put("defender", "defend");
                    map.put("retraso", "delay");
                    map.put("describir", "describe");
                    map.put("desierto", "desert");
                    map.put("diseño", "design");
                    map.put("destruir", "destroy");
                    map.put("desarrollar", "develop");
                    map.put("morir", "die");
                    map.put("diferencia", "difference");
                    map.put("difícil", "difficult");
                    map.put("dirección", "direction");
                    map.put("descubrir", "discover");
                    map.put("distancia", "distance");
                    map.put("dividir", "divide");
                    map.put("médico", "doctor");
                    map.put("perro", "dog");
                    map.put("puerta", "door");
                    map.put("duda", "doubt");
                    map.put("dibujar", "draw");
                    map.put("sueño", "dream");
                    map.put("vestido", "dress");
                    map.put("beber", "drink");
                    map.put("conducir", "drive");
                    map.put("caer", "drop");
                    map.put("seco", "dry");
                    map.put("durante", "during");

                    // E
                    map.put("temprano", "early");
                    map.put("ganar", "earn");
                    map.put("tierra", "earth");
                    map.put("fácil", "easy");
                    map.put("comer", "eat");
                    map.put("borde", "edge");
                    map.put("efecto", "effect");
                    map.put("esfuerzo", "effort");
                    map.put("huevo", "egg");
                    map.put("vacío", "empty");
                    map.put("fin", "end");
                    map.put("enemigo", "enemy");
                    map.put("energía", "energy");
                    map.put("disfrutar", "enjoy");
                    map.put("suficiente", "enough");
                    map.put("entrar", "enter");
                    map.put("igual", "equal");
                    map.put("escapar", "escape");
                    map.put("tarde / noche", "evening");
                    map.put("evento", "event");
                    map.put("cada", "every");
                    map.put("examen", "exam");
                    map.put("ejemplo", "example");
                    map.put("ejercicio", "exercise");
                    map.put("existir", "exist");
                    map.put("explicar", "explain");
                    map.put("ojo", "eye");

                    // F
                    map.put("cara", "face");
                    map.put("hecho", "fact");
                    map.put("fallar", "fail");
                    map.put("caer", "fall");
                    map.put("familia", "family");
                    map.put("lejos", "far");
                    map.put("rápido", "fast");
                    map.put("padre", "father");
                    map.put("miedo", "fear");
                    map.put("sentir", "feel");
                    map.put("pocos", "few");
                    map.put("campo", "field");
                    map.put("luchar", "fight");
                    map.put("llenar", "fill");
                    map.put("encontrar", "find");
                    map.put("dedo", "finger");
                    map.put("fuego", "fire");
                    map.put("pez", "fish");
                    map.put("arreglar", "fix");
                    map.put("bandera", "flag");
                    map.put("plano", "flat");
                    map.put("flor", "flower");
                    map.put("volar", "fly");
                    map.put("seguir", "follow");
                    map.put("comida", "food");
                    map.put("pie", "foot");
                    map.put("fuerza", "force");
                    map.put("bosque", "forest");
                    map.put("olvidar", "forget");
                    map.put("perdonar", "forgive");
                    map.put("formulario / forma", "form");
                    map.put("hacia adelante", "forward");
                    map.put("libre", "free");
                    map.put("amigo", "friend");
                    map.put("frente", "front");
                    map.put("congelado", "frozen");
                    map.put("fruta", "fruit");
                    map.put("lleno", "full");
                    map.put("diversión", "fun");
                    map.put("futuro", "future");

                    // G
                    map.put("juego", "game");
                    map.put("jardín", "garden");
                    map.put("puerta / portón", "gate");
                    map.put("regalo", "gift");
                    map.put("niña", "girl");
                    map.put("dar", "give");
                    map.put("vaso / cristal", "glass");
                    map.put("guante", "glove");
                    map.put("objetivo / gol", "goal");
                    map.put("oro", "gold");
                    map.put("bueno", "good");
                    map.put("gobierno", "government");
                    map.put("agarrar", "grab");
                    map.put("hierba", "grass");
                    map.put("gris", "gray");
                    map.put("genial", "great");
                    map.put("verde", "green");
                    map.put("grupo", "group");
                    map.put("crecer", "grow");
                    map.put("adivinar", "guess");
                    map.put("guía", "guide");

                    // H
                    map.put("hábito", "habit");
                    map.put("mano", "hand");
                    map.put("ocurrir", "happen");
                    map.put("feliz", "happy");
                    map.put("duro", "hard");
                    map.put("sombrero", "hat");
                    map.put("odiar", "hate");
                    map.put("cabeza", "head");
                    map.put("salud", "health");
                    map.put("escuchar", "hear");
                    map.put("corazón", "heart");
                    map.put("pesado", "heavy");
                    map.put("ayudar", "help");
                    map.put("héroe", "hero");
                    map.put("esconder", "hide");
                    map.put("alto", "high");
                    map.put("historia", "history");
                    map.put("sostener", "hold");
                    map.put("agujero", "hole");
                    map.put("hogar", "home");
                    map.put("honesto", "honest");
                    map.put("esperanza", "hope");
                    map.put("caballo", "horse");
                    map.put("hospital", "hospital");
                    map.put("hora", "hour");
                    map.put("casa", "house");
                    map.put("humano", "human");
                    map.put("hambriento", "hungry");
                    map.put("cazar", "hunt");
                    map.put("apresurarse", "hurry");
                    map.put("herir", "hurt");

                    // I
                    map.put("idea", "idea");
                    map.put("imagen", "image");
                    map.put("imaginar", "imagine");
                    map.put("importante", "important");
                    map.put("mejorar", "improve");
                    map.put("incluir", "include");
                    map.put("aumentar", "increase");
                    map.put("informar", "inform");
                    map.put("dentro", "inside");
                    map.put("isla", "island");

                    // J
                    map.put("trabajo", "job");
                    map.put("unirse", "join");
                    map.put("viaje", "journey");
                    map.put("alegría", "joy");
                    map.put("juzgar", "judge");
                    map.put("saltar", "jump");
                    map.put("justo", "just");

                    // K
                    map.put("mantener", "keep");
                    map.put("llave", "key");
                    map.put("amable", "kind");
                    map.put("rey", "king");
                    map.put("cocina", "kitchen");
                    map.put("rodilla", "knee");
                    map.put("cuchillo", "knife");
                    map.put("saber", "know");
                    map.put("conocimiento", "knowledge");

                    // L
                    map.put("lago", "lake");
                    map.put("tierra / aterrizar", "land");
                    map.put("idioma", "language");
                    map.put("grande", "large");
                    map.put("último", "last");
                    map.put("tarde", "late");
                    map.put("reír", "laugh");
                    map.put("ley", "law");
                    map.put("capa", "layer");
                    map.put("liderar", "lead");
                    map.put("hoja", "leaf");
                    map.put("aprender", "learn");
                    map.put("salir", "leave");
                    map.put("pierna", "leg");
                    map.put("carta", "letter");
                    map.put("biblioteca", "library");
                    map.put("vida", "life");
                    map.put("levantar", "lift");
                    map.put("luz", "light");
                    map.put("límite", "limit");
                    map.put("escuchar", "listen");
                    map.put("pequeño", "little");
                    map.put("vivir", "live");
                    map.put("cerrar con llave", "lock");
                    map.put("largo", "long");
                    map.put("mirar", "look");
                    map.put("perder", "lose");
                    map.put("amor", "love");
                    map.put("bajo", "low");
                    map.put("suerte", "luck");

                    // M
                    map.put("máquina", "machine");
                    map.put("mapa", "map");
                    map.put("marca", "mark");
                    map.put("mercado", "market");
                    map.put("significar", "mean");
                    map.put("conocer", "meet");
                    map.put("memoria", "memory");
                    map.put("mensaje", "message");
                    map.put("mente", "mind");
                    map.put("echar de menos", "miss");
                    map.put("error", "mistake");
                    map.put("modelo", "model");
                    map.put("dinero", "money");
                    map.put("mes", "month");
                    map.put("luna", "moon");
                    map.put("mañana", "morning");
                    map.put("madre", "mother");
                    map.put("montaña", "mountain");
                    map.put("boca", "mouth");
                    map.put("mover", "move");
                    map.put("música", "music");

                    // N
                    map.put("nombre", "name");
                    map.put("naturaleza", "nature");
                    map.put("necesitar", "need");
                    map.put("vecino", "neighbor");
                    map.put("nunca", "never");
                    map.put("noticias", "news");
                    map.put("siguiente", "next");
                    map.put("noche", "night");
                    map.put("ruido", "noise");
                    map.put("norte", "north");
                    map.put("nota", "note");
                    map.put("nada", "nothing");
                    map.put("ahora", "now");
                    map.put("número", "number");

                    // O
                    map.put("océano", "ocean");
                    map.put("ofrecer", "offer");
                    map.put("viejo", "old");
                    map.put("abrir", "open");
                    map.put("opinión", "opinion");
                    map.put("naranja", "orange");
                    map.put("orden", "order");
                    map.put("afuera", "outside");
                    map.put("propio", "own");

                    // P
                    map.put("dolor", "pain");
                    map.put("pintar", "paint");
                    map.put("papel", "paper");
                    map.put("padre / madre", "parent");
                    map.put("parque", "park");
                    map.put("parte", "part");
                    map.put("pasar", "pass");
                    map.put("camino", "path");
                    map.put("pagar", "pay");
                    map.put("paz", "peace");
                    map.put("teléfono", "phone");
                    map.put("elegir", "pick");
                    map.put("imagen", "picture");
                    map.put("pieza", "piece");
                    map.put("lugar", "place");
                    map.put("plan", "plan");
                    map.put("planta", "plant");
                    map.put("jugar", "play");
                    map.put("punto", "point");
                    map.put("policía", "police");
                    map.put("pobre", "poor");
                    map.put("poder", "power");
                    map.put("practicar", "practice");
                    map.put("preparar", "prepare");
                    map.put("problema", "problem");
                    map.put("promesa", "promise");
                    map.put("proteger", "protect");
                    map.put("jalar", "pull");
                    map.put("empujar", "push");
                    map.put("poner", "put");

                    // Q
                    map.put("pregunta", "question");
                    map.put("rápido", "quick");
                    map.put("silencioso", "quiet");

                    // R
                    map.put("lluvia", "rain");
                    map.put("alcanzar", "reach");
                    map.put("leer", "read");
                    map.put("listo", "ready");
                    map.put("real", "real");
                    map.put("razón", "reason");
                    map.put("recibir", "receive");
                    map.put("rojo", "red");
                    map.put("recordar", "remember");
                    map.put("respeto", "respect");
                    map.put("volver", "return");
                    map.put("rico", "rich");
                    map.put("correcto / derecho", "right");
                    map.put("subir", "rise");
                    map.put("riesgo", "risk");
                    map.put("río", "river");
                    map.put("carretera", "road");
                    map.put("roca", "rock");
                    map.put("habitación", "room");
                    map.put("raíz", "root");
                    map.put("correr", "run");

                    // S
                    map.put("seguro", "safe");
                    map.put("arena", "sand");
                    map.put("guardar / ahorrar", "save");
                    map.put("decir", "say");
                    map.put("escuela", "school");
                    map.put("mar", "sea");
                    map.put("buscar", "search");
                    map.put("secreto", "secret");
                    map.put("ver", "see");
                    map.put("vender", "sell");
                    map.put("enviar", "send");
                    map.put("sentido", "sense");
                    map.put("compartir", "share");
                    map.put("barco", "ship");
                    map.put("zapato", "shoe");
                    map.put("corto", "short");
                    map.put("mostrar", "show");
                    map.put("simple", "simple");
                    map.put("cantar", "sing");
                    map.put("hermana", "sister");
                    map.put("habilidad", "skill");
                    map.put("cielo", "sky");
                    map.put("dormir", "sleep");
                    map.put("lento", "slow");
                    map.put("pequeño", "small");
                    map.put("sonreír", "smile");
                    map.put("nieve", "snow");
                    map.put("suave", "soft");
                    map.put("soldado", "soldier");
                    map.put("resolver", "solve");
                    map.put("hijo", "son");
                    map.put("canción", "song");
                    map.put("pronto", "soon");
                    map.put("sonido", "sound");
                    map.put("sur", "south");
                    map.put("hablar", "speak");
                    map.put("velocidad", "speed");
                    map.put("gastar", "spend");
                    map.put("deporte", "sport");
                    map.put("primavera", "spring");
                    map.put("estar de pie", "stand");
                    map.put("estrella", "star");
                    map.put("empezar", "start");
                    map.put("quedarse", "stay");
                    map.put("paso", "step");
                    map.put("parar", "stop");
                    map.put("tienda", "store");
                    map.put("tormenta", "storm");
                    map.put("historia", "story");
                    map.put("calle", "street");
                    map.put("fuerte", "strong");
                    map.put("estudiar", "study");
                    map.put("verano", "summer");
                    map.put("sol", "sun");
                    map.put("apoyar", "support");
                    map.put("sobrevivir", "survive");
                    map.put("dulce", "sweet");

                    // T
                    map.put("mesa", "table");
                    map.put("tomar", "take");
                    map.put("hablar", "talk");
                    map.put("alto", "tall");
                    map.put("enseñar", "teach");
                    map.put("equipo", "team");
                    map.put("contar", "tell");
                    map.put("prueba", "test");
                    map.put("agradecer", "thank");
                    map.put("pensar", "think");
                    map.put("lanzar", "throw");
                    map.put("tiempo", "time");
                    map.put("juntos", "together");
                    map.put("mañana", "tomorrow");
                    map.put("tocar", "touch");
                    map.put("pueblo", "town");
                    map.put("tren", "train");
                    map.put("árbol", "tree");
                    map.put("viaje", "trip");
                    map.put("confiar", "trust");
                    map.put("verdad", "truth");
                    map.put("intentar", "try");
                    map.put("girar", "turn");
                    map.put("tipo", "type");

                    // U
                    map.put("tío", "uncle");
                    map.put("entender", "understand");
                    map.put("hasta", "until");
                    map.put("arriba", "up");
                    map.put("usar", "use");
                    map.put("normalmente", "usually");

                    // V
                    map.put("valor", "value");
                    map.put("aldea", "village");
                    map.put("visitar", "visit");
                    map.put("voz", "voice");
                    map.put("votar", "vote");

                    // W
                    map.put("esperar", "wait");
                    map.put("despertar", "wake");
                    map.put("caminar", "walk");
                    map.put("pared", "wall");
                    map.put("querer", "want");
                    map.put("guerra", "war");
                    map.put("cálido", "warm");
                    map.put("agua", "water");
                    map.put("ola", "wave");
                    map.put("camino / manera", "way");
                    map.put("débil", "weak");
                    map.put("arma", "weapon");
                    map.put("tiempo meteorológico", "weather");
                    map.put("semana", "week");
                    map.put("oeste", "west");
                    map.put("blanco", "white");
                    map.put("ancho", "wide");
                    map.put("ganar", "win");
                    map.put("viento", "wind");
                    map.put("ventana", "window");
                    map.put("invierno", "winter");
                    map.put("desear", "wish");
                    map.put("mujer", "woman");
                    map.put("preguntarse", "wonder");
                    map.put("palabra", "word");
                    map.put("trabajar", "work");
                    map.put("mundo", "world");
                    map.put("preocuparse", "worry");
                    map.put("escribir", "write");
                    map.put("incorrecto", "wrong");

                    // X/Y/Z
                    map.put("patio", "yard");
                    map.put("año", "year");
                    map.put("amarillo", "yellow");
                    map.put("ayer", "yesterday");
                    map.put("joven", "young");
                    map.put("cero", "zero");
                    map.put("zona", "zone");

                    // --- EXTRA (tecnología, naturaleza, cotidiano) ---
                    map.put("acceso", "access");
                    map.put("algoritmo", "algorithm");
                    map.put("aplicación", "application");
                    map.put("arreglo", "array");
                    map.put("atributo", "attribute");
                    map.put("copia de seguridad", "backup");
                    map.put("batería", "battery");
                    map.put("navegador", "browser");
                    map.put("error", "bug");
                    map.put("cable", "cable");
                    map.put("caché", "cache");
                    map.put("capacidad", "capacity");
                    map.put("circuito", "circuit");
                    map.put("clic", "click");
                    map.put("nube", "cloud");
                    map.put("código", "code");
                    map.put("comando", "command");
                    map.put("compilador", "compiler");
                    map.put("conexión", "connection");
                    map.put("constante", "constant");
                    map.put("constructor", "constructor");
                    map.put("copiar", "copy");
                    map.put("cursor", "cursor");
                    map.put("dato", "data");
                    map.put("base de datos", "database");
                    map.put("depurar", "debug");
                    map.put("eliminar", "delete");
                    map.put("dispositivo", "device");
                    map.put("directorio", "directory");
                    map.put("descargar", "download");
                    map.put("controlador", "driver");
                    map.put("error", "error");
                    map.put("ejecutar", "execute");
                    map.put("archivo", "file");
                    map.put("carpeta", "folder");
                    map.put("formato", "format");
                    map.put("función", "function");
                    map.put("hardware", "hardware");
                    map.put("anfitrión", "host");
                    map.put("índice", "index");
                    map.put("entrada", "input");
                    map.put("instalar", "install");
                    map.put("instancia", "instance");
                    map.put("interfaz", "interface");
                    map.put("teclado", "keyboard");
                    map.put("librería", "library");
                    map.put("enlace", "link");
                    map.put("lista", "list");
                    map.put("bucle", "loop");
                    map.put("método", "method");
                    map.put("módulo", "module");
                    map.put("monitor", "monitor");
                    map.put("ratón", "mouse");
                    map.put("red", "network");
                    map.put("nodo", "node");
                    map.put("objeto", "object");
                    map.put("operador", "operator");
                    map.put("salida", "output");
                    map.put("paquete", "package");
                    map.put("parámetro", "parameter");
                    map.put("contraseña", "password");
                    map.put("pegar", "paste");
                    map.put("puntero", "pointer");
                    map.put("puerto", "port");
                    map.put("imprimir", "print");
                    map.put("proceso", "process");
                    map.put("programa", "program");
                    map.put("consulta", "query");
                    map.put("cola", "queue");
                    map.put("registro", "record");
                    map.put("actualizar", "refresh");
                    map.put("repositorio", "repository");
                    map.put("solicitud", "request");
                    map.put("reiniciar", "reset");
                    map.put("respuesta", "response");
                    map.put("tiempo de ejecución", "runtime");
                    map.put("pantalla", "screen");
                    map.put("script", "script");
                    map.put("servidor", "server");
                    map.put("sesión", "session");
                    map.put("ajuste", "setting");
                    map.put("software", "software");
                    map.put("ordenar", "sort");
                    map.put("fuente", "source");
                    map.put("pila", "stack");
                    map.put("sentencia", "statement");
                    map.put("cadena", "string");
                    map.put("sintaxis", "syntax");
                    map.put("sistema", "system");
                    map.put("tabla", "table");
                    map.put("terminal", "terminal");
                    map.put("hilo", "thread");
                    map.put("token", "token");
                    map.put("herramienta", "tool");
                    map.put("actualizar", "update");
                    map.put("subir", "upload");
                    map.put("usuario", "user");
                    map.put("valor", "value");
                    map.put("variable", "variable");
                    map.put("versión", "version");
                    map.put("vista", "view");
                    map.put("virtual", "virtual");
                    map.put("sitio web", "website");
                    map.put("ventana", "window");
                    map.put("inalámbrico", "wireless");

                    // --- NATURALEZA / ANIMALES / ALIMENTOS ---
                    map.put("caimán", "alligator");
                    map.put("hormiga", "ant");
                    map.put("abeja", "bee");
                    map.put("escarabajo", "beetle");
                    map.put("mariposa", "butterfly");
                    map.put("camello", "camel");
                    map.put("zanahoria", "carrot");
                    map.put("cereza", "cherry");
                    map.put("pollo", "chicken");
                    map.put("maíz", "corn");
                    map.put("vaca", "cow");
                    map.put("cangrejo", "crab");
                    map.put("cocodrilo", "crocodile");
                    map.put("ciervo", "deer");
                    map.put("delfín", "dolphin");
                    map.put("burro", "donkey");
                    map.put("pato", "duck");
                    map.put("águila", "eagle");
                    map.put("elefante", "elephant");
                    map.put("rana", "frog");
                    map.put("ajo", "garlic");
                    map.put("jirafa", "giraffe");
                    map.put("uva", "grape");
                    map.put("hámster", "hamster");
                    map.put("erizo", "hedgehog");
                    map.put("hipopótamo", "hippo");
                    map.put("medusa", "jellyfish");
                    map.put("limón", "lemon");
                    map.put("león", "lion");
                    map.put("langosta", "lobster");
                    map.put("mango", "mango");
                    map.put("melón", "melon");
                    map.put("mono", "monkey");
                    map.put("seta", "mushroom");
                    map.put("pulpo", "octopus");
                    map.put("cebolla", "onion");
                    map.put("búho", "owl");
                    map.put("loro", "parrot");
                    map.put("melocotón", "peach");
                    map.put("pingüino", "penguin");
                    map.put("pimiento", "pepper");
                    map.put("cerdo", "pig");
                    map.put("piña", "pineapple");
                    map.put("patata", "potato");
                    map.put("calabaza", "pumpkin");
                    map.put("conejo", "rabbit");
                    map.put("arroz", "rice");
                    map.put("salmón", "salmon");
                    map.put("tiburón", "shark");
                    map.put("oveja", "sheep");
                    map.put("gamba", "shrimp");
                    map.put("caracol", "snail");
                    map.put("serpiente", "snake");
                    map.put("espinaca", "spinach");
                    map.put("calamar", "squid");
                    map.put("fresa", "strawberry");
                    map.put("cisne", "swan");
                    map.put("tigre", "tiger");
                    map.put("tomate", "tomato");
                    map.put("atún", "tuna");
                    map.put("pavo", "turkey");
                    map.put("tortuga", "turtle");
                    map.put("sandía", "watermelon");
                    map.put("ballena", "whale");
                    map.put("lobo", "wolf");
                    map.put("gusano", "worm");
                    map.put("cebra", "zebra");

                    // --- CUERPO HUMANO ---
                    map.put("tobillo", "ankle");
                    map.put("cerebro", "brain");
                    map.put("mejilla", "cheek");
                    map.put("barbilla", "chin");
                    map.put("oreja", "ear");
                    map.put("codo", "elbow");
                    map.put("ceja", "eyebrow");
                    map.put("párpado", "eyelid");
                    map.put("frente", "forehead");
                    map.put("cabello", "hair");
                    map.put("talón", "heel");
                    map.put("cadera", "hip");
                    map.put("mandíbula", "jaw");
                    map.put("riñón", "kidney");
                    map.put("labio", "lip");
                    map.put("hígado", "liver");
                    map.put("pulmón", "lung");
                    map.put("músculo", "muscle");
                    map.put("uña", "nail");
                    map.put("cuello", "neck");
                    map.put("nervio", "nerve");
                    map.put("nariz", "nose");
                    map.put("palma", "palm");
                    map.put("costilla", "rib");
                    map.put("hombro", "shoulder");
                    map.put("piel", "skin");
                    map.put("cráneo", "skull");
                    map.put("columna vertebral", "spine");
                    map.put("estómago", "stomach");
                    map.put("garganta", "throat");
                    map.put("pulgar", "thumb");
                    map.put("dedo del pie", "toe");
                    map.put("lengua", "tongue");
                    map.put("diente", "tooth");
                    map.put("vena", "vein");
                    map.put("muñeca", "wrist");

                    // --- ADJETIVOS EXTRA ---
                    map.put("enojado", "angry");
                    map.put("amargo", "bitter");
                    map.put("aburrido", "boring");
                    map.put("valiente", "brave");
                    map.put("cuidadoso", "careful");
                    map.put("inteligente", "clever");
                    map.put("seguro", "confident");
                    map.put("curioso", "curious");
                    map.put("peligroso", "dangerous");
                    map.put("delicioso", "delicious");
                    map.put("diferente", "different");
                    map.put("sucio", "dirty");
                    map.put("distante", "distant");
                    map.put("ansioso", "eager");
                    map.put("enorme", "enormous");
                    map.put("emocionado", "excited");
                    map.put("caro", "expensive");
                    map.put("famoso", "famous");
                    map.put("gordo", "fat");
                    map.put("feroz", "fierce");
                    map.put("frágil", "fragile");
                    map.put("fresco", "fresh");
                    map.put("gracioso", "funny");
                    map.put("generoso", "generous");
                    map.put("gentil", "gentle");
                    map.put("contento", "glad");
                    map.put("precioso", "gorgeous");
                    map.put("agradecido", "grateful");
                    map.put("saludable", "healthy");
                    map.put("útil", "helpful");
                    map.put("enorme", "huge");
                    map.put("humilde", "humble");
                    map.put("hambriento", "hungry");
                    map.put("inteligente", "intelligent");
                    map.put("interesante", "interesting");
                    map.put("celoso", "jealous");
                    map.put("perezoso", "lazy");
                    map.put("ruidoso", "loud");
                    map.put("encantador", "lovely");
                    map.put("afortunado", "lucky");
                    map.put("malo / mezquino", "mean");
                    map.put("desordenado", "messy");
                    map.put("misterioso", "mysterious");
                    map.put("estrecho", "narrow");
                    map.put("nervioso", "nervous");
                    map.put("agradable", "nice");
                    map.put("noble", "noble");
                    map.put("ruidoso", "noisy");
                    map.put("obvio", "obvious");
                    map.put("extraño", "odd");
                    map.put("doloroso", "painful");
                    map.put("paciente", "patient");
                    map.put("perfecto", "perfect");
                    map.put("educado", "polite");
                    map.put("orgulloso", "proud");
                    map.put("redondo", "round");
                    map.put("grosero", "rude");
                    map.put("triste", "sad");
                    map.put("asustado", "scared");
                    map.put("serio", "serious");
                    map.put("afilado", "sharp");
                    map.put("tímido", "shy");
                    map.put("enfermo", "sick");
                    map.put("tonto", "silly");
                    map.put("delgado", "slim");
                    map.put("inteligente", "smart");
                    map.put("suave", "smooth");
                    map.put("agrio", "sour");
                    map.put("cuadrado", "square");
                    map.put("extraño", "strange");
                    map.put("terco", "stubborn");
                    map.put("exitoso", "successful");
                    map.put("repentino", "sudden");
                    map.put("seguro", "sure");
                    map.put("sorprendido", "surprised");
                    map.put("grueso", "thick");
                    map.put("delgado", "thin");
                    map.put("sediento", "thirsty");
                    map.put("reflexivo", "thoughtful");
                    map.put("apretado", "tight");
                    map.put("cansado", "tired");
                    map.put("duro", "tough");
                    map.put("feo", "ugly");
                    map.put("útil", "useful");
                    map.put("violento", "violent");
                    map.put("sabio", "wise");
                    map.put("maravilloso", "wonderful");

                    // --- VERBOS Y TÉRMINOS ACADÉMICOS / TÉCNICOS EXTRA ---
                    map.put("absorber", "absorb");
                    map.put("abstracto", "abstract");
                    map.put("preciso", "accurate");
                    map.put("adquirir", "acquire");
                    map.put("activo", "active");
                    map.put("adaptar", "adapt");
                    map.put("adecuado", "adequate");
                    map.put("admirar", "admire");
                    map.put("adoptar", "adopt");
                    map.put("afectar", "affect");
                    map.put("permitirse", "afford");
                    map.put("agresivo", "aggressive");
                    map.put("alerta", "alert");
                    map.put("asignar", "allocate");
                    map.put("ambiguo", "ambiguous");
                    map.put("analizar", "analyze");
                    map.put("anual", "annual");
                    map.put("ansiedad", "anxiety");
                    map.put("disculparse", "apologize");
                    map.put("aparente", "apparent");
                    map.put("apreciar", "appreciate");
                    map.put("enfoque", "approach");
                    map.put("apropiado", "appropriate");
                    map.put("aproximado", "approximate");
                    map.put("asignar", "assign");
                    map.put("asistir", "assist");
                    map.put("asumir", "assume");
                    map.put("atraer", "attract");
                    map.put("autoridad", "authority");
                    map.put("automático", "automatic");
                    map.put("consciente", "aware");
                    map.put("equilibrio", "balance");
                    map.put("barrera", "barrier");
                    map.put("beneficioso", "beneficial");
                    map.put("mezclar", "blend");
                    map.put("breve", "brief");
                    map.put("transmitir", "broadcast");
                    map.put("calcular", "calculate");
                    map.put("capaz", "capable");
                    map.put("capturar", "capture");
                    map.put("categoría", "category");
                    map.put("desafío", "challenge");
                    map.put("cargar", "charge");
                    map.put("clasificar", "classify");
                    map.put("recolectar", "collect");
                    map.put("combinar", "combine");
                    map.put("comentario", "comment");
                    map.put("comprometerse", "commit");
                    map.put("comunicar", "communicate");
                    map.put("comparar", "compare");
                    map.put("competir", "compete");
                    map.put("complejo", "complex");
                    map.put("concepto", "concept");
                    map.put("confirmar", "confirm");
                    map.put("conflicto", "conflict");
                    map.put("considerar", "consider");
                    map.put("consistir", "consist");
                    map.put("contacto", "contact");
                    map.put("contexto", "context");
                    map.put("continuar", "continue");
                    map.put("contribuir", "contribute");
                    map.put("convertir", "convert");
                    map.put("cooperar", "cooperate");
                    map.put("coordinar", "coordinate");
                    map.put("asesorar", "counsel");
                    map.put("crítico", "critical");
                    map.put("personalizar", "customize");
                    map.put("década", "decade");
                    map.put("declarar", "declare");
                    map.put("dedicar", "dedicate");
                    map.put("definir", "define");
                    map.put("demostrar", "demonstrate");
                    map.put("depender", "depend");
                    map.put("desplegar", "deploy");
                    map.put("derivar", "derive");
                    map.put("detectar", "detect");
                    map.put("determinar", "determine");
                    map.put("distribuir", "distribute");
                    map.put("documento", "document");
                    map.put("dominar", "dominate");
                    map.put("evaluar", "evaluate");
                    map.put("evolucionar", "evolve");
                    map.put("examinar", "examine");
                    map.put("excluir", "exclude");
                    map.put("expandir", "expand");
                    map.put("esperar", "expect");
                    map.put("experiencia", "experience");
                    map.put("explorar", "explore");
                    map.put("exponer", "expose");
                    map.put("extender", "extend");
                    map.put("extraer", "extract");
                    map.put("facilitar", "facilitate");
                    map.put("factor", "factor");
                    map.put("fallo", "failure");
                    map.put("característica", "feature");
                    map.put("filtrar", "filter");
                    map.put("enfocarse", "focus");
                    map.put("generar", "generate");
                    map.put("global", "global");
                    map.put("conceder", "grant");
                    map.put("garantizar", "guarantee");
                    map.put("manejar", "handle");
                    map.put("destacar", "highlight");
                    map.put("hipótesis", "hypothesis");
                    map.put("identificar", "identify");
                    map.put("ignorar", "ignore");
                    map.put("implementar", "implement");
                    map.put("implicar", "imply");
                    map.put("indicar", "indicate");
                    map.put("influencia", "influence");
                    map.put("inicializar", "initialize");
                    map.put("inspeccionar", "inspect");
                    map.put("integrar", "integrate");
                    map.put("interpretar", "interpret");
                    map.put("investigar", "investigate");
                    map.put("involucrar", "involve");
                    map.put("aislar", "isolate");
                    map.put("mantener", "maintain");
                    map.put("gestionar", "manage");
                    map.put("maximizar", "maximize");
                    map.put("medir", "measure");
                    map.put("minimizar", "minimize");
                    map.put("modificar", "modify");
                    map.put("obtener", "obtain");
                    map.put("optimizar", "optimize");
                    map.put("organizar", "organize");
                    map.put("superar", "overcome");
                    map.put("realizar", "perform");
                    map.put("persistir", "persist");
                    map.put("predecir", "predict");
                    map.put("prevenir", "prevent");
                    map.put("producir", "produce");
                    map.put("proveer", "provide");
                    map.put("publicar", "publish");
                    map.put("reconocer", "recognize");
                    map.put("recomendar", "recommend");
                    map.put("recuperar", "recover");
                    map.put("reducir", "reduce");
                    map.put("referencia", "reference");
                    map.put("registrar", "register");
                    map.put("relacionar", "relate");
                    map.put("lanzar", "release");
                    map.put("renderizar", "render");
                    map.put("repetir", "repeat");
                    map.put("reemplazar", "replace");
                    map.put("requerir", "require");
                    map.put("resolver", "resolve");
                    map.put("restringir", "restrict");
                    map.put("recuperar", "retrieve");
                    map.put("revisar", "review");
                    map.put("seleccionar", "select");
                    map.put("separar", "separate");
                    map.put("especificar", "specify");
                    map.put("dividir", "split");
                    map.put("enviar", "submit");
                    map.put("sustituir", "substitute");
                    map.put("resumir", "summarize");
                    map.put("transformar", "transform");
                    map.put("traducir", "translate");
                    map.put("disparar", "trigger");
                    map.put("validar", "validate");
                    map.put("verificar", "verify");

                    return map;
        }
    }

